// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "List.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class List
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator
// App/Edition: ToDo/
// User:        SuperUser Account
namespace AppCode.Data
{
  // This is a generated class for List 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// List data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Label`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class List: AutoGenerated.ZAutoGenList
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.List in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenList: Custom.Data.CustomItem
  {
    /// <summary>
    /// Label as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Label", scrubHtml: true) etc.
    /// </summary>
    public string Label => _item.String("Label", fallback: "");
  }
}