// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "Task.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class Task
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator
// App/Edition: ToDo/
// User:        SuperUser Account
using System;

namespace AppCode.Data
{
  // This is a generated class for Task 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// Task data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Complete`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class Task: AutoGenerated.ZAutoGenTask
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.Task in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenTask: Custom.Data.CustomItem
  {
    /// <summary>
    /// Complete as bool. <br/>
    /// To get nullable use .Get("Complete") as bool?;
    /// </summary>
    public bool Complete => _item.Bool("Complete");

    /// <summary>
    /// DueDate as DateTime.
    /// </summary>
    public DateTime DueDate => _item.DateTime("DueDate");

    /// <summary>
    /// Label as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Label", scrubHtml: true) etc.
    /// </summary>
    public string Label => _item.String("Label", fallback: "");

    /// <summary>
    /// List as single item of List.
    /// </summary>
    /// <remarks>
    /// Generated to only return 1 child because field settings had Multi-Value=false. The type List was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// A single item OR null if nothing found, so you can use ?? to provide alternate objects.
    /// </returns>
    public List List => _list ??= _item.Child<List>("List");
    private List _list;

    /// <summary>
    /// Priority as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Priority", scrubHtml: true) etc.
    /// </summary>
    public string Priority => _item.String("Priority", fallback: "");
  }
}